### PR TITLE
Df online master

### PR DESCRIPTION
**Pull request by youtissoum**

### CODE REVIEW

**Comment by youtissoum** [comment]
oops

**Comment by youtissoum** [comment]
forgot I wasn't on the fork

**Comment by GeorgeRNG** [comment]
I don't really want to make CodeClient interfere with playing other servers, for people who don't have the time to disable and enable the mod with the vanilla launcher~ it also feels pretentious. And the are the Mojang mappings simply better?

**Comment by youtissoum** [comment]
I wasn't trying to push, I just accidentally made the pull request here instead of the fork I use

**Pull request closed without merging**
