### PR TITLE
English (Upside Down) translations

### PR DESCRIPTION
**Pull request by AlignedCookie88**
i added translations for the upside down language option

### CODE REVIEW

**Comment by AlignedCookie88** [comment]
please no more

**Comment by AlignedCookie88** [comment]
Hi CodeClient Developers,

While I understand that you don't want bad-quality translations, I have to press the difficulty of typing upside-down chars.

I don't have a keyboard the size of a country, and I don't think I could afford one, or fit one in my house.

Worst,
AlignedCookie88,
Idiot with too much free time

**Comment by RedVortexDev** [comment]
L getbetter write upside down characters by hand or no mergy :3c
Best,
red vortex _

**Comment by AlignedCookie88** [comment]
please stop being a (british word for donkey with 3 letters starting with a)hole
worst,
alignedcookie88

**Comment by AlignedCookie88** [comment]
i give up

**Pull request closed without merging**
